### ISSUE TITLE
Observed value 

### ISSUE THREAD

**Issue by spholmes** [jfukuyama/phyloseqGraphTest#2]
The number of observed pure edges seems to be too high compared to what I see on the network
when I plot it.
I did a small example with the mice data (I can share this with you)
and the number of pure edges should be about 30, I get 69 (so not even a doubling factor).
When I change the jaccard threshold I then get observed value of 139 for about 25 edges I can see on the plot.

**Comment by jfukuyama** [comment]
Thanks for noticing this, the problem was that when I got rid of the isolates I was using subgraph.edges instead of induced_subgraph and so the graph that got plotted was some weird subset of the true graph. It should be fixed now, I tested your example and the plot seems more in line with the observed number of pure edges now.
